// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnqtlltiwoocwajorglp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRucXRsbHRpd29vY3dham9yZ2xwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMTE0NDQsImV4cCI6MjA2ODg4NzQ0NH0.41ZEEl9xpd6wvpr88wkbjKvmqtfRVMZt7bl8zCzL6os";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});